version: "3.9"

services:
  web:
    build: .
    command: bin/rails server -b 0.0.0.0
    env_file: .env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - $PWD/../db-examatic:/var/lib/postgresql/data
    ports:
      - "5432:5432"
